let classNames = document.querySelector('body').className
document.querySelector('.img-popup').addEventListener('click', function(){
    if(event.target.classList.contains('img1')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img1')
    }
    if(event.target.classList.contains('img2')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img2')
    }
    if(event.target.classList.contains('img3')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img3')
    }
    if(event.target.classList.contains('img4')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img4')
    }
    if(event.target.classList.contains('img5')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img5')
    }
    if(event.target.classList.contains('img6')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img6')
    }
    if(event.target.classList.contains('img7')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img7')
    }
    if(event.target.classList.contains('img8')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img8')
    }
    if(event.target.classList.contains('img9')){
        if(classNames){
            document.querySelector('body').removeAttribute('class')
        }
        document.querySelector('body').classList.toggle('img9')
    }
    
})